### ISSUE TITLE
Tag Release for use with gopkg.in?

### ISSUE THREAD

**Issue by Jmeyering** [agtorre/gocolorize#2]
It would be nice to have this be compatible with gopkg.in.

It would require a tag to v1.0.0

**Comment by agtorre** [comment]
Good idea, I was just looking at gopkg recently. If I have some time this weekend I'll try and add this.

**Comment by agtorre** [comment]
Done -- http://gopkg.in/agtorre/gocolorize.v1

**Comment by Jmeyering** [comment]
Awesome! Thanks so much!
